### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by richburdon** [jong/testing.elasticsearch#3]
1). It would aid the legibility of testing to be able to configure logging (it is currently hardcoded"-Des.logger.level=DEBUG") 

2). Also to have an option to suppress the deprecated "-f" option which causes a warning to be logged.

**Comment by jong** [comment]
I agree this should be configurable. This is another case where when implementing I just went with what I needed at the time.

**Comment by underyx** [comment]
@richburdon to me it looks like you can already specify `foreground=False` to have the library omit the deprecated `-f` flag.
